Add Tasks.ListPaginated
onfleet/gonfleet pull request #12
Opened 2023-04-04 15:59 UTC by shimonp21

2023-04-04 18:52 UTC, naszzz requested changes

2023-04-04 18:52 UTC, naszzz commented on task.go
> +type PaginatedTasks struct {
for consistency with rest of file I suggest naming this `TasksPaginated` instead of `PaginatedTasks`

2023-04-04 18:52 UTC, naszzz commented on task.go
> +	LastID string `json:"lastId"`
change LastID to LastId and add omitempty
refer to to TeamTasks struct in team.go which also includes LastId.

2023-04-04 18:52 UTC, naszzz commented on service/task/client.go
> +func (c *Client) ListPaginated(params onfleet.TaskListQueryParams) (onfleet.PaginatedTasks, error) {
I'd suggest naming this simply List as user can understand from return type that LastId is/can be present for cases where multiple pages are present.

2023-04-06 12:29 UTC, shimonp21 commented
@naszzz Thanks for the quick review! 
[BTW, after this PR is approved + merged, would also be happy for a new release so I can use it in cq-source-onfleet :) ]

2023-04-06 19:13 UTC, naszzz approved these changes
thanks : ) i'm going to create a new release now!

2023-04-06 19:13 UTC, merged